# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models


class SchoolBudgetExpenseComparison(models.Model):
    """
    Budget-vs-actual comparison of a single expense category on a
    school_budget document, generated by
    action_compute_realization() (ssi_school_budget). Built from the
    union of budgeted categories and realized categories, so an
    unbudgeted-but-realized category still surfaces (a finding, not
    a hidden number) and a budgeted-but-unrealized category still
    shows 0% absorption instead of disappearing.
    """

    _name = "school_budget_expense_comparison"
    _description = "School Budget Expense Comparison"

    budget_id = fields.Many2one(
        string="# Budget",
        comodel_name="school_budget",
        required=True,
        ondelete="cascade",
        help="The budget document this comparison line belongs to.",
    )
    expense_category_id = fields.Many2one(
        string="Expense Category",
        comodel_name="school_budget_expense_category",
    )
    budget_amount = fields.Monetary(
        string="Budget Amount",
        currency_field="currency_id",
        help="Sum of (foundation+bos) of expense lines under this "
        "category.",
    )
    realized_amount = fields.Monetary(
        string="Realized Amount",
        currency_field="currency_id",
        help="Sum of realization across all 12 months.",
    )
    realized_amount_ytd = fields.Monetary(
        string="Realized Amount (YTD)",
        currency_field="currency_id",
        help="Sum of realization from month 1 through the current "
        "month, relative to the academic year.",
    )
    variance = fields.Monetary(
        string="Variance",
        currency_field="currency_id",
        help="budget_amount - realized_amount.",
    )
    absorption_rate = fields.Float(
        string="Absorption Rate (%)",
        help="realized_amount / budget_amount * 100. 0 when "
        "budget_amount is 0 (guarded against division by zero). "
        "Values above 100 are valid (over-budget).",
    )
    currency_id = fields.Many2one(
        string="Currency",
        comodel_name="res.currency",
        related="budget_id.currency_id",
        store=True,
        compute_sudo=True,
    )
